name: flockup
description: Flutter meets Meetup. What could go wrong?

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  feather: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
